export type Option = {
	label: string;
	value: string;
};

// Autogenerated types from json result. LP 2026-01-20
export interface Product {
  id: number
  sku: string
  name: string
  slug: string
  type: string
  is_variation: boolean,
  parent?: number
  variations?: Variation[]
  variation?: string
  permalink?: string
  short_description?: string
  description?: string
  on_sale?: boolean
  prices?: Prices
  price_html?: string
  average_rating?: string
  review_count?: number
  images?: any[]
  categories?: any[]
  tags?: any[]
  brands?: any[]
  attributes?: Attribute[]
  grouped_products?: any[]
  has_options?: boolean
  is_purchasable?: boolean
  is_in_stock?: boolean
  is_on_backorder?: boolean
  low_stock_remaining?: any
  stock_availability?: StockAvailability
  sold_individually?: boolean
  add_to_cart?: AddToCart
  extensions?: Extensions
}

export interface Prices {
  price: string
  regular_price: string
  sale_price: string
  price_range: any
  currency_code: string
  currency_symbol: string
  currency_minor_unit: number
  currency_decimal_separator: string
  currency_thousand_separator: string
  currency_prefix: string
  currency_suffix: string
}

export interface Attribute {
  id: number
  name: string
  taxonomy: any
  has_variations: boolean
  terms: Term[]
}

export interface Term {
  id: number
  name: string
  slug: string
}

export interface Variation {
  id: number
  attributes: Attribute2[]
}

export interface Attribute2 {
  name: string
  value: string
}

export interface StockAvailability {
  text: string
  class: string
}

export interface AddToCart {
  text: string
  description: string
  url: string
  single_text: string
  minimum: number
  maximum: number
  multiple_of: number
}

export interface Extensions {}

