export type Option = {
	label: string;
	value: string;
};

export interface VippsBlockConfig {
	BuyNowWithVipps: string;
	logos: Record<string, Record<string, string>>;
	vippssmileurl: string;
	vippsbuynowbutton: string;
	vippsbuynowdescription: string;
	variants: Option[];
	languages: Option[];
}

// Autogenerated types from json result. LP 2026-01-20
export interface Product {
	id: number;
	name: string;
	slug: string;
	variation: string;
	permalink: string;
	sku: string;
	summary: string;
	short_description: string;
	description: string;
	on_sale: boolean;
	prices: Prices;
	average_rating: string;
	review_count: number;
	images: Image[];
	has_options: boolean;
	is_purchasable: boolean;
	is_in_stock: boolean;
	low_stock_remaining: any;
	add_to_cart: AddToCart;
}

export interface Prices {
	currency_code: string;
	currency_symbol: string;
	currency_minor_unit: number;
	currency_decimal_separator: string;
	currency_thousand_separator: string;
	currency_prefix: string;
	currency_suffix: string;
	price: string;
	regular_price: string;
	sale_price: string;
	price_range: any;
}

export interface Image {
	id: number;
	src: string;
	thumbnail: string;
	srcset: string;
	sizes: string;
	name: string;
	alt: string;
}

export interface AddToCart {
	text: string;
	description: string;
}
